# Generated by Django 5.0.1 on 2024-03-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_alter_comericalslider_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='off_price',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
